apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: NFS_SERVER_IP
    path: /NFS_EXPORT_BASE/heimdall/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: heimdall
spec:
  volumeName: heimdall-config-pv
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
