apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: heimdall-nfs
  nfs:
    server: 192.168.2.3
    path: /volume1/k8s/heimdall/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: heimdall-nfs
  resources:
    requests:
      storage: 5Gi
